[package]
name = "typescript-definitions-local"
version = "0.1.0"
edition = "2018"

# Using a fork since the main repo doesn't compile, see https://github.com/arabidopsis/typescript-definitions/issues/8
# The commit is the one that fixes the compilation.
# See https://github.com/onelson/typescript-definitions/commit/f21e330d3a2d3adf9ef7aaae03972e2d80d754ff
[dependencies.typescript-definitions]
git = "https://github.com/onelson/typescript-definitions"
rev = "f21e330d3a2d3adf9ef7aaae03972e2d80d754ff"
features = ["export-typescript"]
