[workspace]
members = [
    "clip-players",
    "core/api",
    "core/lib",
    "core/datamodel",
    "apps/internal/haptic2ahap",
    "third-party/typescript-definitions",
    "unity-editor-plugin",
]
