use cbindgen::Language;

use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_parse_deps(true)
        .with_parse_include(&[
            "api",
            "realtime-audio-to-haptics",
            "lib",
            "clip-players",
            "datamodel",
        ])
        .with_language(Language::C)
        .with_autogen_warning(
            "/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */",
        )
        .with_no_includes()
        .with_sys_include("stdint.h")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("lofelt-sdk.h");
}
