# Builds the Lofelt Wasm NPM package and publishes it to our GitHub registry.
# This workflow is only triggered when a commit is tagged with e.g. "lofelt-wasm-0.1.6"
# and pushed.
name: publish-npm

on:
  push:
    tags:
      - '**lofelt-wasm**'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: publish-npm-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://npm.pkg.github.com
        scope: '@lofelt/lofelt-sdk'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.3.0
      # Don't use v0.10.2 due to https://github.com/rustwasm/wasm-pack/issues/1097,
      # which makes wasm-pack fail on Windows
      with:
        version: 'v0.10.1'

    - name: Run WASM tests
      run: wasm-pack test --node -- --verbose
      working-directory: interfaces/wasm

    - name: Publish NPM package
      run: ./release_npm.sh --latest
      working-directory: interfaces/wasm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


