# Creates the .zip file of the oath-cli and uploads it as a GitHub release
name: release-oath

on:
  push:
    tags:
      - '**oath-cli**'

jobs:
  release-oath:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: release-internal-app-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # GITHUB_REF will be something like refs/tags/haptic2ahap-0.3.0. This step extracts
      # the last part, haptic2ahap-0.3.0, into a RELEASE_TAG variable, and the version,
      # 0.3.0, into a RELEASE_VERSION variable
    - name: Extract version from tag
      run: |
        echo RELEASE_TAG=${GITHUB_REF#refs/*/} >> $GITHUB_ENV
        echo RELEASE_VERSION=${GITHUB_REF#refs/*/*-*} >> $GITHUB_ENV

    - name: Build .zip
      run: ./release-internal-app.sh oath-cli lofelt-analysis ${{ env.RELEASE_VERSION }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        release_name: ${{ env.RELEASE_TAG }}
        draft: false
        prerelease: false

    - name: Upload GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/${{ env.RELEASE_TAG }}.zip
        asset_name: ${{ env.RELEASE_TAG }}.zip
        asset_content_type: application/zip
